/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows.AppWindow;

import javax.swing.JPanel;
import vod.DataBase;

/**
 *
 * @author kamil_2
 */
public class MainAppPanel extends javax.swing.JPanel {
    /**
     * @return the db
     */
    public static DataBase getDb() {
        return db;
    }

    /**
     * @param aDb the db to set
     */
    public static void setDb(DataBase aDb) {
        db = aDb;
    }
    
    private static DataBase db;
    /**
     * Creates new form MainAppPanel
     */
    public MainAppPanel() {
        initComponents();
        setBounds(0, 0, 600, 500);
    }
    private void swapPanels(JPanel panel){
        setVisible(false);
        getParent().add(panel);
        panel.setVisible(true);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bProductsList = new javax.swing.JButton();
        bDistList = new javax.swing.JButton();
        bClientList = new javax.swing.JButton();

        bProductsList.setText("Lista produktow");
        bProductsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductsListActionPerformed(evt);
            }
        });

        bDistList.setText("Lista dystrybutorow");
        bDistList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDistListActionPerformed(evt);
            }
        });

        bClientList.setText("Lista klientow");
        bClientList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClientListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bClientList, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDistList, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bProductsList, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(bProductsList, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bDistList, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bClientList, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bDistListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDistListActionPerformed
        swapPanels(new DistributorList());
    }//GEN-LAST:event_bDistListActionPerformed

    private void bProductsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductsListActionPerformed
        swapPanels(new MultimediaList());
    }//GEN-LAST:event_bProductsListActionPerformed

    private void bClientListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClientListActionPerformed
        swapPanels(new ClientList());
    }//GEN-LAST:event_bClientListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClientList;
    private javax.swing.JButton bDistList;
    private javax.swing.JButton bProductsList;
    // End of variables declaration//GEN-END:variables
}
