/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows.AppWindow;

import Multimedias.LiveStream;
import Multimedias.Movie;
import Multimedias.Multimedia;
import Multimedias.Series;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import vod.DataBase;

/**
 *
 * @author kamil_2
 */
public class MultimediaList extends javax.swing.JPanel {

    /**
     * @return the filtered
     */
    public List<Multimedia> getFiltered() {
        return filtered;
    }

    /**
     * @param filtered the filtered to set
     */
    public void setFiltered(List<Multimedia> filtered) {
        this.filtered = filtered;
    }
    /** 
     * Class created to block editability of cells in table
     */
    public class MyModel extends DefaultTableModel{
        /**
        * @param row
        * @param column
        * @return the db
        */
       @Override
       public boolean isCellEditable(int row, int column) {
          return false;
       }
    }
    
    /**
     *
     * @return
     */
    public synchronized static DataBase getDb() {
        return db;
    }

    /**
     * @param aDb the db to set
     */
    public synchronized static void setDb(DataBase aDb) {
        db = aDb;
    }
    
    private static DataBase db;
    private List<Multimedia> filtered;
    /**
     * Creates new form MultimediaList
     */
    public MultimediaList() {
        initComponents();
        chbMovie.setSelected(true);
        chbSeries.setSelected(true);
        chbLS.setSelected(true);
        setFiltered(new ArrayList());
        getDb().semiDeepCopy(getDb().getMultimedias(), filtered);
        setBounds(0, 0, 600, 500);
        setTable(getDb().getMultimedias());
    }
    private void setTable(List<Multimedia> newList){
        DefaultTableModel dtm = new MyModel();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        tMult.setModel(dtm);
        dtm.setColumnIdentifiers(new String[]{ "id", "nazwa", "kraj", "data produkcji",
            "ocena","dystrybutor", });
        synchronized(getDb()){
            newList.forEach((Multimedia val) -> {
                dtm.addRow(new Object[] { Integer.toString(val.getId()), val.getName(), val.getCountry(), 
                    formatter.format(val.getDateProduction().getTime()), 
                    val.getRating(), val.getDistributor().getDistName() });
            });
        }
    }
    /**
     * swaping current with given JPanel
     */
    private void swapPanels(JPanel panel){
        setVisible(false);
        getParent().add(panel);
        panel.setVisible(true);  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tElement = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbElement = new javax.swing.JComboBox<>();
        bSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        chbLS = new javax.swing.JCheckBox();
        chbSeries = new javax.swing.JCheckBox();
        chbMovie = new javax.swing.JCheckBox();
        bBack = new javax.swing.JButton();
        bChoose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMult = new javax.swing.JTable();

        jLabel1.setText("Wyszukaj po");

        cbElement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nazwie", "aktorze" }));

        bSearch.setText("Szukaj");
        bSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("<html>Wyszukiwane <br>elementy</html>");

        chbLS.setText("Live Stream'y");
        chbLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbLSActionPerformed(evt);
            }
        });

        chbSeries.setText("Seriale");

        chbMovie.setText("Filmy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chbLS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chbSeries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chbMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(chbLS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbMovie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbSeries)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        bBack.setText("Powrot");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });

        bChoose.setText("Wybierz");
        bChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChooseActionPerformed(evt);
            }
        });

        tMult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nazwa", "kraj", "Data Produkcji", "Ocena", "Dystrybutor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tMult.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tMult);
        if (tMult.getColumnModel().getColumnCount() > 0) {
            tMult.getColumnModel().getColumn(0).setPreferredWidth(30);
            tMult.getColumnModel().getColumn(3).setPreferredWidth(50);
            tMult.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(bBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbElement, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tElement, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSearch)
                    .addComponent(tElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bChoose)
                    .addComponent(bBack))
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chbLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbLSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbLSActionPerformed

    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed
        getFiltered().clear();
        getDb().semiDeepCopy(getDb().getMultimedias(), getFiltered());
        if(cbElement.getSelectedIndex() == 0)
            getDb().findMultByName(getFiltered(), tElement.getText(),chbMovie.isSelected(), chbSeries.isSelected(), chbLS.isSelected());
        else {
            chbLS.setSelected(false);
            getDb().findMultByActor(getFiltered(), tElement.getText(),chbMovie.isSelected(), chbSeries.isSelected());
        }
            
        setTable(getFiltered());
        
        
    }//GEN-LAST:event_bSearchActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        swapPanels(new MainAppPanel());
    }//GEN-LAST:event_bBackActionPerformed

    private void bChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChooseActionPerformed
        if(tMult.getSelectedRowCount() != 1 || tMult.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Należy wybrać dokładnie jeden produkt.");
        }
        else{
            int id = Integer.valueOf(String.valueOf(tMult.getValueAt(tMult.getSelectedRow(), 0)));
            Multimedia mult = getDb().findMultById( id );
            if(mult instanceof Movie)
                swapPanels(new MovieDetails(mult));
            if(mult instanceof Series)
                swapPanels(new SerieDetails(mult));
            if(mult instanceof LiveStream)
                swapPanels(new LSDetails(mult));
        }
        
    }//GEN-LAST:event_bChooseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBack;
    private javax.swing.JButton bChoose;
    private javax.swing.JButton bSearch;
    private javax.swing.JComboBox<String> cbElement;
    private javax.swing.JCheckBox chbLS;
    private javax.swing.JCheckBox chbMovie;
    private javax.swing.JCheckBox chbSeries;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tElement;
    private javax.swing.JTable tMult;
    // End of variables declaration//GEN-END:variables
}
