/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows.AppWindow;

import Multimedias.LiveStream;
import Multimedias.Movie;
import Multimedias.Multimedia;
import Multimedias.Series;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author kamil_2
 */
public class Plot extends javax.swing.JPanel {

    private Multimedia mult;
    /**
     * Creates new form Plot
     */
    public Plot() {
        initComponents();
        setBounds(0, 0, 600, 500);
    }

    /**
     * create Plot of given product
     * @param multimediaa
     */
    public Plot(Multimedia multimediaa) {
        this();
        mult = multimediaa;
        JFreeChart chart  = ChartFactory.createBarChart(
            ("Oglądalność \"" + getMult().getName() + "\""),
            "Data", "Ilość odsłon", 
            createDataPlot(),
            PlotOrientation.VERTICAL,
            true, 
            true, 
            false);
        //colors
        CategoryPlot plot = (CategoryPlot) chart.getPlot();  
        plot.getRenderer().setSeriesPaint(0, Color.BLUE);
        //inserting plot in subpanel
        ChartPanel panel = new ChartPanel(chart);
        scPlot.getViewport().add(panel,null);
        panel.setVisible(true);
    }
    private DefaultCategoryDataset createDataPlot(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        SimpleDateFormat formatter = new SimpleDateFormat("MM-yyyy");
        Calendar date = Calendar.getInstance();
        date.set(getMult().getArriveDate().get(Calendar.YEAR), 
                    getMult().getArriveDate().get(Calendar.MONTH), getMult().getArriveDate().get(Calendar.DAY_OF_MONTH),0 , 0, 0);
        for (Integer viewership : getMult().getViewership()) {
            dataset.addValue(viewership, "oglądalność", formatter.format(date.getTime()));
            if(date.get(Calendar.MONTH) < 11)
                date.set(Calendar.MONTH, date.get(Calendar.MONTH) + 1);
            else{
                date.set(Calendar.MONTH, 0);
                date.set(Calendar.YEAR, date.get(Calendar.YEAR) + 1);
            }
        }
        return dataset;
    }
    /**
     * swaping current with given JPanel
     */
    private void swapPanels(JPanel panel){
        setVisible(false);
        getParent().add(panel);
        panel.setVisible(true);  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scPlot = new javax.swing.JScrollPane();
        bBack = new javax.swing.JButton();

        bBack.setText("Powrót");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scPlot)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scPlot, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBack, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        if(getMult() instanceof Movie)
            swapPanels(new MovieDetails(getMult()));
        else{
            if(getMult() instanceof Series)
                swapPanels(new SerieDetails(getMult()));
            else{
                if(getMult() instanceof LiveStream)
                    swapPanels(new LSDetails(getMult()));
                else{
                    System.out.println("Nie znalazłem takiego typu Produktu.");
                }
            }
        }
    }//GEN-LAST:event_bBackActionPerformed

    /**
     * @return the mult
     */
    public Multimedia getMult() {
        return mult;
    }

    /**
     * @param mult the mult to set
     */
    public void setMult(Multimedia mult) {
        this.mult = mult;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBack;
    private javax.swing.JScrollPane scPlot;
    // End of variables declaration//GEN-END:variables
}
