/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows.ControlPanel;

import Multimedias.LiveStream;
import Multimedias.Movie;
import Multimedias.Multimedia;
import Multimedias.Promotion;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import vod.DataBase;

/**
 *
 * @author kamil_2
 */
public class AddPromotionControlPanel extends javax.swing.JPanel {

    /**
     * @return the db
     */
    public static DataBase getDb() {
        return db;
    }

    /**
     * @param aDb the db to set
     */
    public static void setDb(DataBase aDb) {
        db = aDb;
    }

    private Promotion prom;
    private Multimedia mult;
    private static DataBase db;
    /**
     * Creates new form AddPromotionControlPanel
     */
    public AddPromotionControlPanel() {
        this.setMult(null);
        this.setProm(null);
        initComponents();
        setBounds(0, 0, 600, 500);
        SpinnerModel model = new SpinnerNumberModel(5, 5, 50, 1);
        sDiscount.setModel(model);
    }
    /**
     * Creates new form AddPromotionControlPanel
     * @param multimedia
     */
    public AddPromotionControlPanel(Multimedia multimedia) {
        this();
        setMult(multimedia);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbYearFrom = new javax.swing.JComboBox<>();
        cbDayFrom = new javax.swing.JComboBox<>();
        cbMonthFrom = new javax.swing.JComboBox<>();
        cbYearTo = new javax.swing.JComboBox<>();
        cbDayTo = new javax.swing.JComboBox<>();
        cbMonthTo = new javax.swing.JComboBox<>();
        sDiscount = new javax.swing.JSpinner();
        bAddPromotion = new javax.swing.JButton();
        bAddWithoutPromotion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Dodawanie promocji");

        jLabel2.setText("Od kiedy*");

        jLabel3.setText("Do kiedy*");

        jLabel4.setText("<html>Wartość procentowa <br>obnizki</html> ");

        cbYearFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rok", "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));

        cbDayFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dzien", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbDayFrom.setToolTipText("");

        cbMonthFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miesiac", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        cbYearTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rok", "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));

        cbDayTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dzien", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbDayTo.setToolTipText("");

        cbMonthTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miesiac", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        bAddPromotion.setText("Dodaj promocje");
        bAddPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddPromotionActionPerformed(evt);
            }
        });

        bAddWithoutPromotion.setText("Dodaj produkt bez promocji");
        bAddWithoutPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddWithoutPromotionActionPerformed(evt);
            }
        });

        jLabel5.setText("*Wymagane pola promocji");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(bAddPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAddWithoutPromotion)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(146, 146, 146)
                                    .addComponent(cbDayFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbMonthFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbYearFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(97, 97, 97)
                                        .addComponent(cbDayTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbMonthTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbYearTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbDayFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMonthFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbYearFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbDayTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMonthTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbYearTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddWithoutPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAddPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * swaping current with given JPanel
     */
    private void swapPanels(JPanel panel){
        setVisible(false);
        getParent().add(panel);
        panel.setVisible(true);  
    }
    
    /**
     * Check if the Data have proper values and send notifications for user
     */
    private boolean properData(){
        if(cbDayFrom.getSelectedIndex() <= 0 || cbMonthFrom.getSelectedIndex() <= 0 || 
                cbYearFrom.getSelectedIndex() <= 0 || cbDayTo.getSelectedIndex() <= 0 || 
                cbMonthTo.getSelectedIndex() <= 0 || cbYearTo.getSelectedIndex() <= 0 )
        {
            JOptionPane.showMessageDialog(null, "Proszę sprawdzić, czy wszystkie wymagane pola, \nzostały wypełnione poprawnie.");
            return false;
        }
        else{
            if((cbDayTo.getSelectedIndex() < cbDayFrom.getSelectedIndex() && 
                    cbMonthTo.getSelectedIndex() == cbMonthFrom.getSelectedIndex()&& 
                    cbYearTo.getSelectedIndex() == cbYearFrom.getSelectedIndex() ) ||
                    (cbMonthTo.getSelectedIndex() < cbMonthFrom.getSelectedIndex()&& 
                    cbYearTo.getSelectedIndex() == cbYearFrom.getSelectedIndex() ) ||
                    cbYearTo.getSelectedIndex() < cbYearFrom.getSelectedIndex())
            {
                JOptionPane.showMessageDialog(null, "Data do której trwa promocja nie moze wsytapić, \nprzed datą rozpoczęcia promocji.");
                return false;
            }
        }
        return true;
    }
    private void bAddPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddPromotionActionPerformed
        Calendar dateFrom = Calendar.getInstance(), dateTo = Calendar.getInstance();
        if(properData()){
            dateFrom.set(Calendar.YEAR, cbYearFrom.getSelectedIndex() + 1899);
            dateFrom.set(Calendar.MONTH, cbMonthFrom.getSelectedIndex());
            dateFrom.set(Calendar.DAY_OF_MONTH, cbDayFrom.getSelectedIndex());
            dateTo.set(Calendar.YEAR, cbYearFrom.getSelectedIndex() + 1899);
            dateTo.set(Calendar.MONTH, cbMonthFrom.getSelectedIndex());
            dateTo.set(Calendar.DAY_OF_MONTH, cbDayFrom.getSelectedIndex());
            prom = new Promotion(dateFrom, dateTo, (int)sDiscount.getValue());
            if( getMult() instanceof Movie )
                ((Movie) getMult()).setPromotion(prom);
            else{
                ((LiveStream) getMult()).setPromotion(prom);
            }
            getDb().getMultimedias().add(getMult());
            swapPanels(new MainControlPanel());
        }
    }//GEN-LAST:event_bAddPromotionActionPerformed

    private void bAddWithoutPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddWithoutPromotionActionPerformed
        getDb().getMultimedias().add(getMult());
        swapPanels(new MainControlPanel());
    }//GEN-LAST:event_bAddWithoutPromotionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddPromotion;
    private javax.swing.JButton bAddWithoutPromotion;
    private javax.swing.JComboBox<String> cbDayFrom;
    private javax.swing.JComboBox<String> cbDayTo;
    private javax.swing.JComboBox<String> cbMonthFrom;
    private javax.swing.JComboBox<String> cbMonthTo;
    private javax.swing.JComboBox<String> cbYearFrom;
    private javax.swing.JComboBox<String> cbYearTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner sDiscount;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the prom
     */
    public Promotion getProm() {
        return prom;
    }

    /**
     * @param prom the prom to set
     */
    public void setProm(Promotion prom) {
        this.prom = prom;
    }

    /**
     * @return the mult
     */
    public Multimedia getMult() {
        return mult;
    }

    /**
     * @param mult the mult to set
     */
    public void setMult(Multimedia mult) {
        this.mult = mult;
    }
}
