/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows.ControlPanel;


import Multimedias.LiveStream;
import Multimedias.Movie;
import Multimedias.Series;
import javax.swing.JPanel;
import vod.DataBase;

/**
 *
 * @author kamil_2
 */
public class MainControlPanel extends javax.swing.JPanel {

    /**
     * @return the db
     */
    public static DataBase getDb() {
        return db;
    }

    /**
     * @param aDb the db to set
     */
    public static void setDb(DataBase aDb) {
        db = aDb;
    }
    private static DataBase db;
    /**
     * Creates new form MainControlPanel
     */
    public MainControlPanel() {
        initComponents();
        setBounds(0, 0, 600, 500);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAddDistributor = new javax.swing.JButton();
        bAddClient = new javax.swing.JButton();
        bAddMovie = new javax.swing.JButton();
        bAddSerie = new javax.swing.JButton();
        bAddLS = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        bLoad = new javax.swing.JButton();
        bSubPrice = new javax.swing.JButton();

        bAddDistributor.setText("Dodaj dystrybutora");
        bAddDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddDistributorActionPerformed(evt);
            }
        });

        bAddClient.setText("Dodaj klienta");
        bAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddClientActionPerformed(evt);
            }
        });

        bAddMovie.setText("Dodaj Film");
        bAddMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddMovieActionPerformed(evt);
            }
        });

        bAddSerie.setText("Dodaj Serial");
        bAddSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddSerieActionPerformed(evt);
            }
        });

        bAddLS.setText("Dodaj wydarzenie na żywo");
        bAddLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddLSActionPerformed(evt);
            }
        });

        bSave.setText("Zapisz Symulacje");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bLoad.setText("Wczytaj Symulacje");
        bLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoadActionPerformed(evt);
            }
        });

        bSubPrice.setText("Zmień ceny Subskrypcji");
        bSubPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bAddDistributor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAddClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAddMovie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAddLS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAddSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSubPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(bAddDistributor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAddClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAddMovie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAddSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAddLS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSubPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bLoad)
                .addGap(100, 100, 100))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * swaping current with given JPanel
     */
    private void swapPanels(JPanel panel){
        setVisible(false);
        getParent().add(panel);
        panel.setVisible(true);  
    }
    private void bAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddClientActionPerformed
        swapPanels(new AddClientControlPanel());
    }//GEN-LAST:event_bAddClientActionPerformed

    private void bAddMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddMovieActionPerformed
        swapPanels(new AddMultimediaControlPanel(new Movie(), false));
    }//GEN-LAST:event_bAddMovieActionPerformed

    private void bAddDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddDistributorActionPerformed
        swapPanels(new AddDistributorControlPanel());          
    }//GEN-LAST:event_bAddDistributorActionPerformed

    private void bAddSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddSerieActionPerformed
        swapPanels(new AddMultimediaControlPanel(new Series(), false));
    }//GEN-LAST:event_bAddSerieActionPerformed

    private void bAddLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddLSActionPerformed
        swapPanels(new AddMultimediaControlPanel(new LiveStream(), false));   
    }//GEN-LAST:event_bAddLSActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        db.serializeAll();
    }//GEN-LAST:event_bSaveActionPerformed

    private void bLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoadActionPerformed
        db.deserializeAll();
        
    }//GEN-LAST:event_bLoadActionPerformed

    private void bSubPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubPriceActionPerformed
        swapPanels(new SubPrice());          
    }//GEN-LAST:event_bSubPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddClient;
    private javax.swing.JButton bAddDistributor;
    private javax.swing.JButton bAddLS;
    private javax.swing.JButton bAddMovie;
    private javax.swing.JButton bAddSerie;
    private javax.swing.JButton bLoad;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bSubPrice;
    // End of variables declaration//GEN-END:variables

    
}
